name : deploy EC2 instance

on :
 push :
  branches : main



jobs: 
  deploy :
    name: deploy 
    runs-on : ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ec2_aws:$(date +%s)

    - name: setting EC2 instance credentials
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        user: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        run: |
          ssh user@host
          docker stop $(docker ps -q)
          docker run --expose=5000 $(docker ps -q)
        
    